# NLP Project - Text Generation Using LSTM
### Group Members:
<ul>
  <li>Hams Ansari (16P-6056)</li>
  <li>Sohaib Jawad (16P-6012)</li>
  <li>Mustafa Hassan (16P-6004)</li>
</ul>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import re
from string import punctuation as punc
from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_extraction.stop_words module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_extraction.text. Anything that cannot be imported from sklearn.feature_extraction.text is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
#This function reads files
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

In [ ]:
X = read_file('drive/My Drive/Colab Notebooks/moby_dick_four_chapters.txt')

In [ ]:
#Normalizing Corpus
X = X.lower()

### Tokenize and Clean Text

In [ ]:
X = X.split('\n')

In [ ]:
data = []

#This function tokenizes documents in corpus
def convert_to_list(X,data):
    for row in range(0,len(X)):
        data.insert(len(data),X[row].split(' '))
    return data 

In [ ]:
convert_to_list(X,data)

[['call',
  'me',
  'ishmael.',
  '',
  'some',
  'years',
  'ago--never',
  'mind',
  'how',
  'long'],
 ['precisely--having',
  'little',
  'or',
  'no',
  'money',
  'in',
  'my',
  'purse,',
  'and',
  'nothing'],
 ['particular',
  'to',
  'interest',
  'me',
  'on',
  'shore,',
  'i',
  'thought',
  'i',
  'would',
  'sail',
  'about',
  'a'],
 ['little',
  'and',
  'see',
  'the',
  'watery',
  'part',
  'of',
  'the',
  'world.',
  '',
  'it',
  'is',
  'a',
  'way',
  'i',
  'have',
  'of'],
 ['driving',
  'off',
  'the',
  'spleen',
  'and',
  'regulating',
  'the',
  'circulation.',
  '',
  'whenever',
  'i'],
 ['find',
  'myself',
  'growing',
  'grim',
  'about',
  'the',
  'mouth;',
  'whenever',
  'it',
  'is',
  'a',
  'damp,'],
 ['drizzly',
  'november',
  'in',
  'my',
  'soul;',
  'whenever',
  'i',
  'find',
  'myself',
  'involuntarily'],
 ['pausing',
  'before',
  'coffin',
  'warehouses,',
  'and',
  'bringing',
  'up',
  'the',
  'rear',
  'of',
  'every'],
 ['fu

In [ ]:
def remove_punctuations(data):  
    for ch in punc:
        for i in range(0,len(data)):
            for j in data[i]: 
                if ch == j:
                    data[i].remove(ch)

    for i in range(0,len(data)):
        for j in data[i]:
            if j == '':
                #print(1)
                data[i].remove(j) 

    return data 

In [ ]:
#removing punctuations from tokenized list
data = remove_punctuations(data)

In [1]:
#data

In [ ]:
#List containing tokens without punctuations
tokens = []

for i in range(0,len(data)):
    for j in range(0,len(data[i])):
        tokens.append(data[i][j])

In [2]:
#tokens

In [ ]:
len(tokens)

11029

In [ ]:
# organize into sequences of tokens
train_len = 25+1 # 25 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [ ]:
' '.join(text_sequences[0])

'call me ishmael. some years ago--never mind how long precisely--having little or no money in my purse, and nothing particular to interest me on shore, i'

In [ ]:
' '.join(text_sequences[1])

'me ishmael. some years ago--never mind how long precisely--having little or no money in my purse, and nothing particular to interest me on shore, i thought'

In [ ]:
len(text_sequences)

11003

In [ ]:
import keras
from keras.preprocessing.text import Tokenizer

In [ ]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [ ]:
sequences[0]

[921,
 23,
 920,
 45,
 352,
 3445,
 221,
 112,
 144,
 3443,
 44,
 33,
 38,
 351,
 7,
 20,
 917,
 3,
 142,
 269,
 5,
 3440,
 23,
 26,
 3438,
 6]

In [ ]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'to',
 6: 'i',
 7: 'in',
 8: 'that',
 9: 'his',
 10: 'it',
 11: 'he',
 12: 'was',
 13: 'but',
 14: 'as',
 15: 'with',
 16: 'at',
 17: 'this',
 18: 'for',
 19: 'is',
 20: 'my',
 21: 'you',
 22: 'be',
 23: 'me',
 24: 'from',
 25: 'all',
 26: 'on',
 27: 'not',
 28: 'up',
 29: 'there',
 30: 'one',
 31: 'into',
 32: 'what',
 33: 'or',
 34: 'about',
 35: 'by',
 36: 'were',
 37: 'so',
 38: 'no',
 39: 'had',
 40: 'out',
 41: 'have',
 42: 'an',
 43: 'upon',
 44: 'little',
 45: 'some',
 46: 'they',
 47: 'if',
 48: 'old',
 49: 'like',
 50: 'now',
 51: 'thought',
 52: 'would',
 53: 'over',
 54: 'him',
 55: 'such',
 56: 'which',
 57: 'then',
 58: 'could',
 59: 'very',
 60: 'when',
 61: 'sort',
 62: 'said',
 63: 'me,',
 64: 'these',
 65: 'most',
 66: 'been',
 67: 'harpooneer',
 68: 'it,',
 69: 'your',
 70: 'go',
 71: 'do',
 72: 'must',
 73: 'down',
 74: 'did',
 75: 'first',
 76: 'i,',
 77: 'here',
 78: 'more',
 79: 'though',
 80: 'never',
 81: 'much',
 82

In [ ]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

921 : call
23 : me
920 : ishmael.
45 : some
352 : years
3445 : ago--never
221 : mind
112 : how
144 : long
3443 : precisely--having
44 : little
33 : or
38 : no
351 : money
7 : in
20 : my
917 : purse,
3 : and
142 : nothing
269 : particular
5 : to
3440 : interest
23 : me
26 : on
3438 : shore,
6 : i


In [ ]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 1533),
             ('ishmael.', 29),
             ('some', 732),
             ('years', 83),
             ('ago--never', 6),
             ('mind', 137),
             ('how', 294),
             ('long', 243),
             ('precisely--having', 10),
             ('little', 739),
             ('or', 948),
             ('no', 871),
             ('money', 92),
             ('in', 5462),
             ('my', 1758),
             ('purse,', 43),
             ('and', 9486),
             ('nothing', 253),
             ('particular', 124),
             ('to', 6261),
             ('interest', 22),
             ('on', 1454),
             ('shore,', 25),
             ('i', 6240),
             ('thought', 624),
             ('would', 624),
             ('sail', 78),
             ('about', 910),
             ('a', 10142),
             ('see', 364),
             ('the', 15149),
             ('watery', 26),
             ('part', 208),
             ('of', 82

In [ ]:
vocabulary_size = len(tokenizer.word_counts)

In [ ]:
vocabulary_size

3447

In [ ]:
import numpy as np

In [ ]:
sequences = np.array(sequences)

In [ ]:
sequences

array([[ 921,   23,  920, ...,   26, 3438,    6],
       [  23,  920,   45, ..., 3438,    6,   51],
       [ 920,   45,  352, ...,    6,   51,    6],
       ...,
       [   9,  916,   12, ...,    9,  270,   49],
       [ 916,   12,  156, ...,  270,   49,    2],
       [  12,  156, 3439, ...,   49,    2, 3447]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [ ]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

### Train / Test Split

In [ ]:
from keras.utils import to_categorical

In [ ]:
sequences

array([[ 921,   23,  920, ...,   26, 3438,    6],
       [  23,  920,   45, ..., 3438,    6,   51],
       [ 920,   45,  352, ...,    6,   51,    6],
       ...,
       [   9,  916,   12, ...,    9,  270,   49],
       [ 916,   12,  156, ...,  270,   49,    2],
       [  12,  156, 3439, ...,   49,    2, 3447]])

In [ ]:
sequences[:,:-1]

array([[ 921,   23,  920, ...,   23,   26, 3438],
       [  23,  920,   45, ...,   26, 3438,    6],
       [ 920,   45,  352, ..., 3438,    6,   51],
       ...,
       [   9,  916,   12, ..., 3446,    9,  270],
       [ 916,   12,  156, ...,    9,  270,   49],
       [  12,  156, 3439, ...,  270,   49,    2]])

In [ ]:
sequences[:,-1]

array([   6,   51,    6, ...,   49,    2, 3447])

In [ ]:
X = sequences[:,:-1]

In [ ]:
y = sequences[:,-1]

In [ ]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [ ]:
seq_len = X.shape[1]

In [ ]:
seq_len

25

In [ ]:
# define model
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 25, 25)            86200     
_________________________________________________________________
lstm_3 (LSTM)                (None, 25, 150)           105600    
_________________________________________________________________
lstm_4 (LSTM)                (None, 150)               180600    
_________________________________________________________________
dense_3 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_4 (Dense)              (None, 3448)              520648    
Total params: 915,698
Trainable params: 915,698
Non-trainable params: 0
_________________________________________________________________


---

----

In [ ]:
# fit model
model.fit(X, y, batch_size=64, epochs=200,verbose=1)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/200
11003/11003 [==============================] - 28s 3ms/step - loss: 7.1045 - accuracy: 0.0480
Epoch 2/200
11003/11003 [==============================] - 27s 2ms/step - loss: 6.5864 - accuracy: 0.0530
Epoch 3/200
11003/11003 [==============================] - 27s 2ms/step - loss: 6.4265 - accuracy: 0.0530
Epoch 4/200
11003/11003 [==============================] - 27s 2ms/step - loss: 6.2754 - accuracy: 0.0588
Epoch 5/200
11003/11003 [==============================] - 27s 2ms/step - loss: 6.1158 - accuracy: 0.0676
Epoch 6/200
11003/11003 [==============================] - 27s 2ms/step - loss: 5.9923 - accuracy: 0.0713
Epoch 7/200
11003/11003 [==============================] - 27s 2ms/step - loss: 5.8805 - accuracy: 0.0735
Epoch 8/200
11003/11003 [==============================] - 27s 2ms/step - loss: 5.7788 - accuracy: 0.0753
Epoch 9/200
11003/11003 [==============================] - 27s 2ms/step - loss: 5.6911 - accuracy: 0.0772
Epoch 10/200
11003/11003 [====================

# Generating New Text

In [ ]:
from random import randint
# from pickle import load
# from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [ ]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

### Grab a random seed sequence

In [ ]:
text_sequences[0]

['call',
 'me',
 'ishmael.',
 'some',
 'years',
 'ago--never',
 'mind',
 'how',
 'long',
 'precisely--having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse,',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore,',
 'i']

In [ ]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [ ]:
random_seed_text = text_sequences[random_pick]

In [ ]:
random_seed_text

['so',
 'blended',
 'their',
 'hues',
 'together;',
 'and',
 'it',
 'was',
 'only',
 'by',
 'the',
 'sense',
 'of',
 'weight',
 'and',
 'pressure',
 'that',
 'i',
 'could',
 'tell',
 'that',
 'queequeg',
 'was',
 'hugging',
 'me.',
 'my']

In [ ]:
seed_text = ' '.join(random_seed_text)

In [ ]:
seed_text

'so blended their hues together; and it was only by the sense of weight and pressure that i could tell that queequeg was hugging me. my'

In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=26)

'other legs were tufted to lodge from the little devil did not seem to fancy such dry sort of fare that go to that "don\'t showed'